# Generated by Django 5.1.2 on 2024-11-20 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
