# Generated by Django 5.1.2 on 2024-10-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=25, unique=True)),
                ('phone', models.IntegerField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
