# Generated by Django 5.1.2 on 2024-10-25 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='phone',
        ),
    ]
