# Generated by Django 5.1.2 on 2024-10-25 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_remove_userdata_phone'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdata',
            table='userdata',
        ),
    ]
