# Generated by Django 5.1.2 on 2024-10-28 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_alter_userdata_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otpverification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='userdata',
            name='phone',
            field=models.CharField(default='0000000000', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits only.', regex='^\\d{10}')]),
        ),
        migrations.AlterModelTable(
            name='otpverification',
            table='otp',
        ),
    ]
