# Generated by Django 5.1.2 on 2024-10-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_otpverification_email_otpverification_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
