# Generated by Django 5.1.2 on 2024-11-16 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_order_address_order_product'),
        ('users', '0002_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='users.address'),
        ),
    ]
